---
# tasks file for vsftpd
- name: Install Vsftpd
  package:
    name: vsftpd
    state: present
  tags: vsftpd

- name: Install configuration file
  template:
    src:   vsftpd.conf
    dest: /etc/vsftpd.conf
    mode: '0600'
  notify: restart vsftpd
  tags: vsftpd

- name: service is started
  service:
    name: vsftpd
    state: started
    enabled: true
  tags: vsftpd
